#19 - container implements interop container interface too.
northwoods/container pull request #20
Opened 2018-09-18 08:17 UTC by Musiksammler

Solution to issue #19

2018-09-18 13:25 UTC, shadowhand requested changes

2018-09-18 13:25 UTC, shadowhand commented on src/InjectorContainer.php
> +use Interop\Container\ContainerInterface as InteropContainerInterface;
Interface is not available because [`container-interop/container-interop`](https://packagist.org/packages/container-interop/container-interop) is not installed.

2018-09-20 11:47 UTC, Musiksammler commented on src/InjectorContainer.php
> +use Interop\Container\ContainerInterface as InteropContainerInterface;
I've added it to composer.json

2018-09-20 13:52 UTC, shadowhand approved these changes

2018-09-20 13:53 UTC, merged

2018-09-20 13:53 UTC, shadowhand commented
Thanks!

2018-09-20 13:55 UTC, shadowhand commented
Released in version 3.2.0.